# Generated by Django 5.0.2 on 2024-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
